MODULE = base
IRSIMDIR = ..
SRCS =	access.c binsim.c cad_dir.c config.c conn_list.c eval.c fio.c \
	hist.c hist_io.c intr.c mem.c netupdate.c network.c \
	newrstep.c nsubrs.c parallel.c prints.c rsim.c sched.c sim.c \
	sstep.c stack.c tpos.c usage.c ${OTHER_SRCS}

include ${IRSIMDIR}/defs.mak
include ${IRSIMDIR}/rules.mak
